Feature/react components
bhskr44/book-store pull request #1
Opened 2022-12-09 21:45 UTC by bhskr44

# Highlights

✔️ Add React Dom
✔️ Default view set to bookList
✔️ Check the Status button added to the category Page
✔️ Profile Page added
✔️ Add Book Component Added
✔️ No stylings added

2022-12-09 23:05 UTC, Gambit142 requested changes
Hi @bhskr44 👋, 

Good job so far!

## Highlights
- All linters checks pass ✔️ 
- `react-router-dom` is present in the `package.json` file ✔️ 
- Page navigation is done using `react-router-dom` ✔️

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
### I am making these suggestions here because I can't make inline comments on the _**README.md**_ file.

- [x] Under the `Tech Stack` section, kindly remove the `Server` and `Database` subsections. No technology in this category was used for this project. 👍 
- [x] For the `Key Features` section, you have the feature from the **_Math Magician_** project, kindly remove this. 💻 
- [x] For the `Future Features` section, you have the feature from the **_Math Magician_** project, kindly remove this. 💻 
- [ ] Kindly work on the `Show Your Support` section of the README.md file. You can describe how people can show their support for this project. 👍 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-09 23:05 UTC, Gambit142 commented on src/App.js
> +        </Routes>
- [x] Kindly remove the `Profile` component. The requirements state that there should be two links in the navbar, one for the `Homepage` and the other for the `Categories`. 👍

2022-12-09 23:05 UTC, Gambit142 commented on src/components/navBar.js
> +      </ul>
- [x] For the navbar, kindly use the `Link` component that `react-router-dom` provides instead of the `a` tag you used. One of the great advantages of using `React` is that it easily creates **_Single Page Applications_**. Using the `Link` component is essential to this feature. You can read this [article](https://v5.reactrouter.com/web/api/Link) to get a better understanding. 👍

2022-12-09 23:05 UTC, Gambit142 commented on src/components/profile.js
> +export default profile;
- [ ] Kindly delete this file. You don't need it, so there is no need to include it. This way, you would be satisfying the [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) (You Aint Gonna Need It) principle. 💻

2022-12-09 23:22 UTC, bhskr44 commented on src/components/profile.js
> +export default profile;
Hi @Gambit142 , Thanks for the suggestions but It seems the design we had been provided has a button for the profile section.  That is the reason I added it.

![image](https://user-images.githubusercontent.com/30873007/206810979-2f8500a3-d8a8-403f-adc6-3c00681042c6.png)

2022-12-10 03:49 UTC, Kamba56 approved these changes
Hi @bhskr44 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
## Highlights
- [x] All linters passed!👏👏👏
- [x] Great use of Github workflow!👏👏👏
- [x] Descriptive PR!👏👏👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 03:49 UTC, Kamba56 commented on src/components/singleBook.js
> +    alert('Do You really want to delete this book from the list');
- [Optional] It is [best js practice](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md#javascript-in-the-browser) not to use alert. Kindly remove this please.

2022-12-15 09:52 UTC, merged